import {APP_VERSION,esc,uid,now,validateManifest,validateLibrary,compareVersion,moduleEvidence,recommend,reviewQueue} from './domain.js';
import * as store from './storage.js';
import {makeZip} from './zip.js';
import {reviewFiles,questionPrompt} from './review.js';

const main=document.querySelector('main'),connection=document.querySelector('#connection');
let library,baseLibrary,profile,data,currentDraft,currentAttempt,saveChain=Promise.resolve(),saveError=null,swReady=false,registration,preparedExport,updateCandidate,toastTimer;
let routeEpoch=0,updating=false;
const time=v=>new Date(v).toLocaleString('zh-Hant',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const level=['L0 · 起點觀察','L1 · 系統 mental model','L2 · Technical reasoning','L3 · 架構判斷','L4 · Founder judgment'];
const button=(action,label,secondary=false,extra='')=>`<button type="button" class="button${secondary?' secondary':''}" data-action="${action}" ${extra}>${esc(label)}</button>`;
function toast(text){document.querySelector('#toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>document.querySelector('#toast').textContent='',5000);}
function status(){connection.textContent=swReady?(navigator.onLine?'離線教材已準備':'離線 · 可繼續學習'):(navigator.onLine?'離線準備未完成':'離線準備未確認');connection.classList.toggle('not-ready',!swReady);}
function showError(e){toast(e.message||String(e));}
function queueSave(){
 if(!currentDraft)return;
 const snapshot=structuredClone(currentDraft);const label=document.querySelector('#draft-status');if(label)label.textContent='正在保存到這部裝置…';
 saveChain=saveChain.catch(()=>{}).then(async()=>{try{await store.saveDraft(snapshot);saveError=null;const el=document.querySelector('#draft-status');if(el&&currentDraft?.id===snapshot.id)el.textContent=`已保存到這部裝置 · ${time(snapshot.updatedAt||now())}`;}catch(e){saveError=e;const el=document.querySelector('#draft-status');if(el){el.textContent='保存失敗。請保留此頁，不要關閉；稍後重試。';el.style.color='var(--error)';}throw e;}});
 // Attach a rejection handler immediately; flush still observes the error.
 saveChain.catch(()=>{});
}
async function flush(){if(currentDraft)queueSave();await saveChain;if(saveError)throw saveError;}
async function refreshData(){data=await store.records();}
async function composeLibrary(){baseLibrary=await store.activeLibrary();library=structuredClone(baseLibrary);const meta=await store.all('meta');const packs=meta.filter(v=>v.id.startsWith('pack:')).map(v=>v.pack);library.packs=packs.map(p=>({id:p.id,title:p.title,version:p.version,provenance:p.provenance}));for(const p of packs)library.scenarios.push(...p.scenarios.map(s=>({...s,supplementary:p.id})));validateLibrary(library);}
async function verifiedDownload(manifest){validateManifest(manifest);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{
 const res=await fetch(manifest.url,{cache:'no-store',credentials:'same-origin',signal:controller.signal});if(!res.ok||!res.headers.get('content-type')?.includes('json'))throw Error('教材下載未成功；請確認網絡，原教材保留。');
 const bytes=await res.arrayBuffer();if(bytes.byteLength!==manifest.bytes)throw Error('教材不完整，原教材保留。');
 const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==manifest.sha256)throw Error('教材完整性驗證失敗，原教材保留。');
 const l=validateLibrary(JSON.parse(new TextDecoder().decode(bytes)));if(l.version!==manifest.libraryVersion)throw Error('教材與版本清單不一致。');return l;
 }finally{clearTimeout(timer);}}
async function fetchManifest(){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch('./content/manifest.json',{cache:'no-store',credentials:'same-origin',signal:controller.signal});if(!r.ok||!r.headers.get('content-type')?.includes('json'))throw Error('不能取得版本清單。請連線重試。');return validateManifest(await r.json());}finally{clearTimeout(timer);}}
function offlineNote(){return swReady?'完整教材及介面已存於裝置。仍請用飛行模式關閉重開一次，確認真實裝置可用。':'教材已保存；App 介面尚未確認離線準備。保持連線，待頁面顯示「離線教材已準備」。';}
function head(title,text=''){return `<div class="page-head"><h1>${esc(title)}</h1>${text?`<p>${esc(text)}</p>`:''}</div>`;}
function nav(page){document.querySelectorAll('.nav a').forEach(a=>{a.removeAttribute('aria-current');if(a.dataset.page===page)a.setAttribute('aria-current','page');});}
function home(){const next=recommend(library,data),seen=new Set(data.attempts.map(a=>a.scenario.id)),draft=data.drafts.at(-1);
 main.innerHTML=head('學會看懂系統。','不用先學會寫 code。從一個情境開始，練習思考、追問及判斷。')+
 `<p class="home-phrase">先用自己的話回答。<br>再看看，你的理解能否<strong>用到下一個產品</strong>。</p>`+
 `<div class="start-zone"><div><h2>${draft?'繼續上次的思考':esc(next.scenario.title)}</h2><p>${draft?esc(draft.scenario.title)+' · 原始答案草稿已保存':esc(next.reason)}<br>約 ${draft?draft.scenario.estimatedMinutes:next.scenario.estimatedMinutes} 分鐘；隨時可以離開。</p></div>${button(draft?'resume':'start',draft?'繼續作答':'Start · 開始學習',false,draft?`data-id="${draft.id}"`:'')}</div>`+
 `<p class="meta">已作答 ${seen.size}／${library.scenarios.length} 個情境 · 沒有固定學習次數 · 完成度不等於 mastery</p>`+
 `<section class="section"><h2>這次只做一件事</h2><p class="prose">找出已知、假設及不知道的部分。題目可以沒有問題，也可以資訊不足；你不必猜一個看似專業的答案。</p></section>`+
 `<section class="section"><div class="notice ${swReady?'success':''}"><strong>${swReady?'可以離線學習':'首次離線準備'}</strong><p>${offlineNote()}</p></div></section>`+
 `<div class="actions"><a class="button secondary" href="#review">準備 Windows AI 回顧</a><a class="button text" href="#settings">離線與教材設定</a></div>`+
 `<p class="footer-note">學習紀錄只在此裝置。不提供備份還原；清除網站資料可能永久失去紀錄。教材公開；你的答案不會自動上傳。</p>`;
}
function libraryPage(query='',filter='all'){let count=0;
 const chapters=library.modules.filter(m=>filter==='all'||String(m.level)===filter).map((m,i)=>{const ss=library.scenarios.filter(s=>s.moduleId===m.id&&(!query||[s.title,s.situation,m.title].some(v=>v.toLowerCase().includes(query.toLowerCase()))));if(!ss.length)return '';count+=ss.length;const e=moduleEvidence(m,library,data);
 return `<details class="chapter" ${query?'open':''}><summary><span class="number">${String(m.order+1).padStart(2,'0')}</span><span class="row-main"><strong>${esc(m.title)}</strong><span class="meta">${level[m.level]} · ${e.unique}/${e.total} 已作答</span></span></summary>${ss.map(s=>`<div class="row"><div class="row-main"><span class="row-title">${esc(s.title)}</span>${s.supplementary?'<span class="badge">AI 補充 · 未專業驗證</span>':''}<p>${data.attempts.some(a=>a.scenario.id===s.id)?'已有紀錄 · 可重新作答':'未作答'} · 約 ${s.estimatedMinutes} 分鐘</p></div><a class="row-button" href="#scenario/${s.id}" aria-label="開始：${esc(s.title)}">開始</a></div>`).join('')}</details>`;
 }).join('');
 main.innerHTML=head('完整教材','依理解而非日期前進。建議先按順序建立概念，也可以自由探索；題目類型在作答後才顯示。')+
 `<div class="filter-bar"><label class="screen-reader" for="search">搜尋教材</label><input id="search" placeholder="搜尋情境或主題" value="${esc(query)}" type="search"><label class="screen-reader" for="level-filter">學習層次</label><select id="level-filter"><option value="all">全部層次</option>${level.map((x,i)=>`<option value="${i}" ${filter===String(i)?'selected':''}>${esc(x)}</option>`).join('')}</select></div><p class="meta">教材 v${esc(library.version)} · ${count} 個情境</p><div class="section">${chapters||'<p class="empty">沒有符合的情境。請換一個搜尋字或層次。</p>'}</div><p class="footer-note">完整 core 已編寫；教學效益與個人 mastery 仍需實際學習及 AI review 驗證。</p>`;
}
function progress(){main.innerHTML=head('你的學習證據','原始答案會保留。反思、提示與 retest 另記錄；這裡的狀態是暫定線索，不是自動評分。')+
 `<section><h2>目前理解的輪廓</h2>${library.modules.map(m=>{const e=moduleEvidence(m,library,data);return `<div class="row"><div class="row-main"><span class="row-title">${esc(m.title)}</span><p>${esc(e.status)}<br>無提示 ${e.independent} 次 · 轉移／重測 ${e.transfer} 次 · 界線反思 ${e.boundaryEvidence} 次<br>${esc(e.estimate)}</p></div><span class="meta">${e.unique}/${e.total}</span></div>`;}).join('')}</section>`+
 `<section class="section history"><h2>原始作答及 retest</h2>${data.attempts.length?data.attempts.slice().reverse().map(a=>`<details><summary>${esc(a.scenario.title)} ${a.isRetest?'<span class="badge">重新作答</span>':''}<span class="meta"> · ${time(a.submittedAt)}</span></summary><p class="meta">信心 ${a.confidence}/5 · 提交前提示 ${a.hintsUsed}/3 · scenario v${esc(a.scenario.version)}</p><div class="original">${esc(a.answer)}</div>${data.events.filter(e=>e.attemptId===a.id&&e.kind==='reflection').map(e=>`<div class="section"><p><strong>事後反思（非原始答案）</strong></p><p>${esc(e.note||'未填文字')}</p><p class="meta">自評：${esc(selfLabels[e.selfAssessment]||e.selfAssessment)} · boundary：${esc(e.boundary||'未記錄')}</p>${e.misconception?`<p class="meta">自述待驗證誤解：${esc(e.misconception)}</p>`:''}</div>`).join('')}<a href="#attempt/${a.id}">閱讀分析及補充反思</a></details>`).join(''):'<p class="empty">還沒有已提交的答案。從第一個情境建立起點紀錄。</p>'}</section>`+
 (data.drafts.length?`<section class="section"><h2>未完成草稿</h2>${data.drafts.map(d=>`<div class="row"><div class="row-main"><strong>${esc(d.scenario.title)}</strong><p>草稿，不作 mastery 證據</p></div><a href="#draft/${d.id}">繼續</a></div>`).join('')}</section>`:'');}
const selfLabels={'needs-work':'我發現有誤解','uncertain':'我仍不確定','can-explain':'我能用自己的話解釋（待驗證）'};
async function begin(s,draftId){await refreshData();let d=draftId?await store.get('drafts',draftId):data.drafts.find(d=>d.scenario.id===s.id);
 if(!d){const preference=await store.get('meta','answer-mode');d={answerMode:preference?.value||'open',practiceAfterExplanation:data.events.some(e=>(e.kind==='analysis-viewed'||e.kind==='ai-reviewed'&&e.reviewed)&&((e.scenarioId===s.id)||data.attempts.some(a=>a.id===e.attemptId&&a.scenario.id===s.id))),id:uid(),scenario:structuredClone(s),libraryVersion:library.version,startedAt:now(),answer:'',confidence:null,hintsUsed:0,hintHistory:[],isRetest:data.attempts.some(a=>a.scenario.id===s.id)};await store.saveDraft(d);}
 if(d.answerMode==='closed'&&!d.scenario.closed)d.answerMode='open';currentDraft=d;currentAttempt=null;renderScenario();}
function referenceFor(s){const updated=library.scenarios.find(x=>x.id===s.id&&x.situation.replaceAll("给","給")===s.situation.replaceAll("给","給")&&x.question===s.question);return s.closed?s:(updated||s);}
function teaching(s){const r=referenceFor(s);return `<section class="analysis"><h2>這題的答案</h2><p>${esc(r.teaching?.answer||r.analysis.explanation)}</p><h3>為甚麼</h3><p>${esc(r.analysis.explanation)}</p>${r.teaching?`<h3>用一個例子理解</h3><p>${esc(r.teaching.example)}</p>`:''}${r.closed?`<h3>逐個選項看</h3>${r.closed.options.map(o=>`<p><strong>${o.id===r.closed.correctOptionId?'✓ 較合理':'其他選項'}：${esc(o.text)}</strong><br>${esc(o.explanation)}</p>`).join('')}`:''}<h3>下一步可以怎樣確認</h3><p>${esc(r.analysis.evidence)}</p><details><summary>想再了解：如何問工程師</summary><p>${esc(r.analysis.engineerQuestion)}</p><p>${esc(r.analysis.boundary)}</p></details>${r.version!==s.version?'<p class="meta">使用新版教材解說；你當時的題目及答案沒有改動。</p>':''}</section>`;}
function renderScenario(){const d=currentDraft,s=d.scenario,closed=d.answerMode==='closed';
 main.innerHTML=`<a href="#home">回到學習</a>`+head(s.title)+`<p class="scenario-story">${esc(s.situation)}</p><p class="question">${esc(s.question)}</p><div class="field"><label for="answer-mode">作答方式</label><select id="answer-mode"><option value="open" ${!closed?'selected':''}>Open Answer · 用自己的話回答</option><option value="closed" ${closed?'selected':''} ${!s.closed?'disabled':''}>Close Answer · 選答案，立即看解說</option></select></div>${d.practiceAfterExplanation?'<p class="notice">解說後練習：這次重答會另作記錄。</p>':''}<form id="answer-form">${closed?`<fieldset class="choice-list field"><legend>${esc(s.closed.question)}</legend>${s.closed.options.map(o=>`<label><input type="radio" name="choice" value="${o.id}" ${d.selectedOptionId===o.id?'checked':''} required>${esc(o.text)}</label>`).join('')}</fieldset>`:`<div class="field"><label for="answer">你的原始想法</label><textarea id="answer" maxlength="30000" required placeholder="我認為…，因為…；我還需要知道…">${esc(d.answer)}</textarea></div>`}<p id="draft-status" class="draft-status" role="status">草稿已保存到這部裝置</p><fieldset class="field"><legend>你有多大信心？</legend><div class="confidence">${['很不確定','有點把握','一半一半','頗有把握','很有把握'].map((x,i)=>`<label><input type="radio" name="confidence" value="${i+1}" ${d.confidence===i+1?'checked':''} required><span>${x}</span></label>`).join('')}</div></fieldset><div class="hint-area">${button('hint',d.hintsUsed<3?`需要提示 · ${d.hintsUsed}/3`:'已使用所有提示',true,d.hintsUsed>=3?'disabled':'')}${s.hints.slice(0,d.hintsUsed).map((h,i)=>`<p class="hint">提示 ${i+1} · ${esc(h)}</p>`).join('')}</div><div class="actions"><button class="button" type="submit">${closed?'提交選擇，立即看答案':'保存答案，準備 AI 批改'}</button>${button('read-draft','先看解說',true)}</div><p class="meta">${closed?'離線也能核對選項。答對這題不等於已全面掌握。':'保存後按「AI 批改」，複製整段到 Gemini 或其他 AI。FTL 不會自行判斷自由文字。'}</p></form><div id="draft-teaching"></div>`;
 document.querySelector('#answer')?.addEventListener('input',e=>{d.answer=e.target.value;queueSave();});
 document.querySelector('#answer-mode').addEventListener('change',async e=>{d.answerMode=e.target.value;if(d.answerMode==='closed')d.optionsSeenBeforeOpen=true;await store.put('meta',{id:'answer-mode',value:d.answerMode});queueSave();await flush();renderScenario();});
 document.querySelectorAll('[name=choice]').forEach(el=>el.addEventListener('change',e=>{d.selectedOptionId=e.target.value;queueSave();}));
 document.querySelectorAll('[name=confidence]').forEach(el=>el.addEventListener('change',e=>{d.confidence=Number(e.target.value);queueSave();}));
 document.querySelector('#answer-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await flush();const a=await store.submit(d);currentDraft=null;location.hash=`attempt/${a.id}`;}catch(err){showError(err);b.disabled=false;}});
}
async function showAttempt(a){currentAttempt=a;currentDraft=null;const reviewed=reviewQueue(data).some(e=>e.scenarioId===a.scenario.id);
 main.innerHTML=`<a href="#progress">回到紀錄</a>`+head(a.scenario.title)+`<p class="scenario-story">${esc(a.scenario.situation)}</p><p class="question">${esc(a.scenario.question)}</p><section class="section"><h2>你當時的答案</h2><p class="meta">信心 ${a.confidence}/5 · 提示 ${a.hintsUsed}/3 · ${a.practiceAfterExplanation?'解說後練習':'已保留原始作答'}</p><div class="original">${esc(a.answer)}</div>${a.openDraft?`<details><summary>切換模式前的文字草稿</summary><div class="original">${esc(a.openDraft)}</div></details>`:''}</section>${a.closedResult?`<div class="notice section"><strong>${a.closedResult.correct?'這個選擇正確':'這個選擇不合適'}</strong><p>下方逐項解釋原因。這是本題選項的核對結果。</p></div>${teaching(a.scenario)}`:'<p class="notice section">尚未批改。把完整題目及你的答案交給 AI，便可得到針對你答案的解說。</p>'}<div class="actions">${button('ai-grade','AI 批改 · 複製到 Gemini')}${button('ai-elaborate','複製深入解說 prompt',true)}${!a.closedResult?button('read-attempt','查看參考解說',true):''}</div><div id="copy-result" role="status"></div><div class="field section"><label><input id="ai-reviewed" type="checkbox" ${reviewed?'checked':''}> 我已找 AI 批改，加入溫習區</label><p class="meta">由你自行勾選；不用貼回 AI 的結果。</p></div><div id="attempt-teaching"></div><div class="actions"><a class="button secondary" href="#scenario/${a.scenario.id}">再答一次</a><a class="button secondary" href="#practice">到溫習區</a><a class="button text" href="#home">繼續學習</a></div>`;
 main.insertAdjacentHTML('beforeend',`<details class="section"><summary>記下一點自己的理解（可選）</summary><form id="reflection-form"><label for="understanding">現在能否用自己的話解釋？</label><select id="understanding"><option value="uncertain">仍不確定</option><option value="needs-work">發現有誤解</option><option value="can-explain">能用自己的話解釋，仍需換題驗證</option></select><div class="field"><label for="reflection">我學到甚麼？</label><textarea id="reflection" class="small" maxlength="10000"></textarea></div><div class="field"><label for="boundary">哪一步仍需要工程師確認？</label><textarea id="boundary" class="small" maxlength="10000"></textarea></div><button class="button" type="submit">保存心得</button></form></details>`);
 document.querySelector('#reflection-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await store.appendEvent({kind:'reflection',attemptId:a.id,selfAssessment:document.querySelector('#understanding').value,note:document.querySelector('#reflection').value,boundary:document.querySelector('#boundary').value,source:'learner-self-report',mastery:'unverified'});await refreshData();toast('心得已另存，不改動原始答案。');}catch(err){showError(err);}finally{b.disabled=false;}});
 document.querySelector('#ai-reviewed').addEventListener('change',async e=>{const el=e.target;try{await store.appendEvent({kind:'ai-reviewed',attemptId:a.id,scenarioId:a.scenario.id,reviewed:el.checked,source:'learner-self-report'});await refreshData();toast(el.checked?'已加入溫習區':'已取消溫習標記');}catch(err){el.checked=!el.checked;showError(err);}});
 if(a.closedResult)await markRead(a);
}
async function markRead(a){await store.appendEvent({kind:'analysis-viewed',attemptId:a.id,scenarioId:a.scenario.id});await refreshData();}
function practice(){const queue=reviewQueue(data);main.innerHTML=head('溫習區','這些題目你已找 AI 批改。換一個情境再練習，看看自己能否用上剛學的判斷。')+(queue.length?queue.map(q=>{const a=data.attempts.find(a=>a.id===q.attemptId);if(!a)return '';return `<section class="section"><h2>${esc(a.scenario.title)}</h2><p>複製完整指引到 Gemini 或另一個 AI。它會先出新情境，等你回答後才解說。</p><div class="actions">${button('ai-practice','複製不同情境溫習 prompt',false,`data-id="${a.id}"`)}<a href="#attempt/${a.id}">回看原題</a></div></section>`;}).join(''):'<p class="empty">在作答紀錄勾選「我已找 AI 批改」，這裡就會出現該題。</p>')+'<div id="copy-result" role="status"></div>';}
async function copyPrompt(a,purpose){const prompt=questionPrompt(a,referenceFor(a.scenario),purpose);let copied=false;try{await navigator.clipboard.writeText(prompt);copied=true;}catch{}const el=document.querySelector('#copy-result');el.innerHTML=copied?'<p class="notice success">已複製。開啟 Gemini 或其他 AI，貼上整段並傳送即可。</p>':`<label for="prompt-copy">未能自動複製。請全選下方文字，再複製到 AI。</label><textarea id="prompt-copy" readonly>${esc(prompt)}</textarea>${button('select-prompt','全選文字',true)}`;await store.appendEvent({kind:copied?'ai-prompt-copied':'ai-prompt-prepared',attemptId:a.id,scenarioId:a.scenario.id,purpose});}
function review(){preparedExport=null;main.innerHTML=head('帶到 Windows，繼續思考。','匯出一個檔案。新 agent 會收到完整上下文、原始證據及 review prompt，不用你重新解釋。')+
 `<ol class="steps"><li><div><strong>準備 Review Pack</strong><p>在手機離線產生 ZIP，包含完整學習紀錄及指引。</p></div></li><li><div><strong>傳到 Windows</strong><p>用你選擇的跨裝置傳檔工具；不需要 FTL 帳號或雲端同步。</p></div></li><li><div><strong>交給任何 AI</strong><p>上傳 ZIP，說：「請按 START-HERE.md 開始。」若不支援 ZIP，解壓後上傳裡面檔案。</p></div></li><li><div><strong>回顧，再做個人化題目</strong><p>AI 先整理重點，再一次一題。結束會給下一個 chat 可直接續接的文件。</p></div></li></ol>`+
 `<div class="notice"><strong>分享前知道包含甚麼</strong><p>所有已提交原始答案、信心、提示、反思、版本及未完成草稿。共 ${data.attempts.length} 次提交、${data.drafts.length} 個草稿。只在你選擇分享後離開裝置。</p></div><div class="actions">${button('prepare-export','準備一個 ZIP 檔')}</div><div id="export-result" aria-live="polite"></div>`+
 `<section class="section"><h2>Windows 會做甚麼</h2><p class="prose">回顧證據、追問推理、安排轉移及 hidden retest，並指出哪些事要交給專家。新答案會放在 continuation 文件，第一版不自動匯回手機。</p></section><section class="section"><h2>帶回補充教材</h2><p>AI 可以依 PACK-SPEC.md 產生 JSON 補充題；在「設定」預覽及匯入。補充題會標示 AI 來源，不接受 AI 修改歷史或自動升級 mastery。</p><a class="button text" href="#settings">匯入補充教材</a></section><p class="footer-note">ZIP 用於 review，不提供備份還原。匯出本身可離線；實際傳檔是否需網絡取決於你的工具。</p>`;}
function settings(){const packs=library.packs||[];
 main.innerHTML=head('離線與教材設定','教材更新、App 更新及原始紀錄分開處理。下載不完整時，繼續使用原版本。')+
 `<div class="notice ${swReady?'success':''}"><strong>${swReady?'離線教材已準備':'離線準備尚未確認'}</strong><p>${offlineNote()}</p></div>`+
 `<section class="section"><h2>這部裝置</h2><p>答案、草稿及心得保存在此瀏覽器；只有你主動複製或匯出才會分享。網站由 GitHub Pages 提供，託管方可能記錄連線資訊。FTL 沒有分析追蹤或自動 AI 連線。</p><p>App v${APP_VERSION} · Core v${esc(baseLibrary.version)}<br>${library.scenarios.length} 個情境 · ${data.attempts.length} 次提交</p><div class="actions">${button('storage-status','檢查儲存狀態',true)}${button('persist','申請持久儲存',true)}</div><p id="storage-status" class="meta section" role="status"></p><p class="meta">系統不保證永久保存；你已選擇不做備份還原。清除網站資料、移除或裝置損壞可能失去紀錄。</p></section>`+
 `<section class="section"><h2>教材更新</h2><p>有網絡時檢查；完整下載及校驗後才切換。原始紀錄保留當時題目版本。</p><div class="actions">${button('check-update','檢查教材更新',true)}</div><div id="update-result" class="update-box" role="status"></div></section>`+
 `<section class="section"><h2>App 更新</h2><p>更新介面前會先保存草稿。下載失敗時，離線舊版本仍保留。</p><div class="actions">${button('check-app','檢查 App 更新',true)}</div><div id="app-update" class="update-box" role="status">${registration?.waiting?button('apply-app','新版本已下載 · 重新開啟'):''}</div></section>`+
 `<section class="section"><h2>AI 補充題</h2><p>只接受教材 JSON；不接受 AI 評分或學習紀錄匯入。不覆寫歷史或舊題目。</p><label for="pack-file" class="meta">選擇 supplementary pack（最多 5 MB）</label><input id="pack-file" class="file-input" type="file" accept=".json,application/json"><div id="pack-preview" role="status"></div>${packs.length?`<ul>${packs.map(p=>`<li>${esc(p.title)} · v${esc(p.version)} · AI 內容待驗證</li>`).join('')}</ul>`:''}</section>`+
 `<section class="section"><h2>加入 iPhone 主畫面</h2><ol><li>用 Safari 開啟正式 HTTPS 網址，不需要登入。</li><li>在 Safari 的分享選單選「加入主畫面」，以 Web App 開啟。</li><li>從主畫面開啟，等待離線教材準備完成。</li><li>飛行模式關閉重開，測試閱讀、作答及保存。</li></ol><p class="meta">手機請使用 GitHub Pages 正式網址。電腦 localhost 的作答不會自動搬到手機。</p></section><section class="section"><h2>教材來源及限制</h2><p>${esc(library.methodology)}</p><ul>${(library.sources||[]).map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></li>`).join('')}</ul><p class="meta">來源連結需網絡；情境、提示及分析不依賴連線。</p></section>`;
 document.querySelector('#pack-file').addEventListener('change',previewPack);
}
let packCandidate;
function validatePack(p){
 if(!p||p.schemaVersion!==1||p.kind!=='ftl-supplementary'||!p.id||!/^[a-z0-9-]{3,80}$/.test(p.id)||!/^\d+\.\d+\.\d+$/.test(p.version)||p.baseLibraryVersion!==baseLibrary.version||typeof p.title!=='string'||!p.title.trim()||!p.provenance||typeof p.provenance.model!=='string'||typeof p.provenance.generatedAt!=='string'||!Array.isArray(p.provenance.evidenceAttemptIds)||!Array.isArray(p.scenarios)||!p.scenarios.length||p.scenarios.length>100)throw Error('補充題格式或教材版本不符。請按 PACK-SPEC.md 重新產生。');
 if((library.packs||[]).some(x=>x.id===p.id))throw Error('同名教材包已存在；第一版不覆寫教材包。');
 for(const s of p.scenarios){if(!s.id.startsWith(p.id+'-')||!Number.isInteger(s.level)||s.level<0||s.level>4||!Number.isFinite(s.estimatedMinutes)||s.estimatedMinutes<1||s.estimatedMinutes>120)throw Error('補充題識別或時間格式錯誤。');}
 if(p.provenance.evidenceAttemptIds.some(id=>!data.attempts.some(a=>a.id===id)))throw Error('補充題引用了這部裝置不存在的 attemptId。');
 validateLibrary({...library,scenarios:[...library.scenarios,...p.scenarios]});return p;
}
async function previewPack(e){packCandidate=null;const el=document.querySelector('#pack-preview');try{const file=e.target.files[0];if(!file)return;if(file.size>5_000_000)throw Error('教材包大於 5 MB，未匯入。');packCandidate=validatePack(JSON.parse(await file.text()));el.innerHTML=`<div class="notice"><strong>${esc(packCandidate.title)}</strong><p>${packCandidate.scenarios.length} 個新增情境 · AI：${esc(packCandidate.provenance.model)} · 此內容未經專業驗證。</p><ul>${packCandidate.scenarios.map(s=>`<li>${esc(s.title)}</li>`).join('')}</ul></div><div class="actions">${button('install-pack','接受並加入教材')}${button('cancel-pack','取消',true)}</div>`;}catch(err){el.textContent=err.message;}}
async function route(){const epoch=++routeEpoch;try{await flush();const hash=location.hash.slice(1)||'home',parts=hash.split('/');await refreshData();if(epoch!==routeEpoch)return;currentDraft=null;currentAttempt=null;nav(['scenario','draft','attempt'].includes(parts[0])?'home':parts[0]);
 if(parts[0]==='home')home();else if(parts[0]==='library')libraryPage();else if(parts[0]==='progress')progress();else if(parts[0]==='practice')practice();else if(parts[0]==='review')review();else if(parts[0]==='settings')settings();else if(parts[0]==='scenario'){const s=library.scenarios.find(s=>s.id===parts[1]);if(!s)throw Error('找不到情境。');await begin(s);}else if(parts[0]==='draft'){const d=await store.get('drafts',parts[1]);if(!d)throw Error('找不到草稿。');await begin(d.scenario,d.id);}else if(parts[0]==='attempt'){const a=await store.get('attempts',parts[1]);if(!a)throw Error('找不到作答。');await showAttempt(a);}else{location.hash='home';return;}
 window.scrollTo(0,0);main.focus({preventScroll:true});
 }catch(e){showError(e);if(!library)fatal(e);}}
function fatal(e){main.innerHTML=head('暫時未能準備學習空間')+`<div class="notice error">${esc(e.message)}。請確認使用 HTTPS 或 localhost、允許網站儲存並連線重試。</div><div class="actions">${button('reload','重新開啟')}</div><p class="meta section">沒有刪除任何既有紀錄。</p>`;}
async function swCheck(){if(!registration?.active)return;try{const ready=await new Promise((resolve)=>{const channel=new MessageChannel();const timer=setTimeout(()=>resolve(false),5000);channel.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data.ready===true);};registration.active.postMessage({type:'CHECK_READY'},[channel.port2]);});swReady=ready&&!!baseLibrary;status();}catch{swReady=false;status();}}
async function setupWorker(){if(!('serviceWorker' in navigator))return;registration=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});registration.addEventListener('updatefound',()=>{const w=registration.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'){swCheck();if(registration.waiting)toast('App 新版本已下載，可在設定更新。');}});});await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('離線介面下載未完成')),20000))]);await swCheck();if(['','home','settings'].includes(location.hash.slice(1)))await route();}
document.addEventListener('click',async e=>{const target=e.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;
 try{if(action==='reload'){location.reload();return;}if(action==='start'){location.hash=`scenario/${recommend(library,data).scenario.id}`;return;}if(action==='resume'){location.hash=`draft/${target.dataset.id}`;return;}
 if(action==='select-prompt'){document.querySelector('#prompt-copy').select();return;}
 if(action==='ai-grade'||action==='ai-elaborate'||action==='ai-practice'){const a=action==='ai-practice'?data.attempts.find(a=>a.id===target.dataset.id):currentAttempt;await copyPrompt(a,action==='ai-grade'?'grade':action==='ai-practice'?'practice':'elaborate');return;}
 if(action==='read-draft'){currentDraft.practiceAfterExplanation=true;await flush();await store.appendEvent({kind:'analysis-viewed',draftId:currentDraft.id,scenarioId:currentDraft.scenario.id});document.querySelector('#draft-teaching').innerHTML=teaching(currentDraft.scenario);return;}
 if(action==='read-attempt'){await markRead(currentAttempt);document.querySelector('#attempt-teaching').innerHTML=teaching(currentAttempt.scenario);return;}
 if(action==='hint'){if(!currentDraft||currentDraft.hintsUsed>=3)return;currentDraft.hintsUsed++;currentDraft.hintHistory.push({number:currentDraft.hintsUsed,at:now()});queueSave();await flush();renderScenario();return;}
 if(action==='prepare-export'){target.disabled=true;await flush();await refreshData();const files=reviewFiles(library,data,profile);const bytes=makeZip(files),date=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Singapore'});preparedExport={file:new File([bytes],`FTL-Review-${date}.zip`,{type:'application/zip'}),report:new Blob([files['START-HERE.md']+'\n\n---\n\n'+files['learning-report.md']],{type:'text/markdown;charset=utf-8'}),files};const supported=!!navigator.canShare?.({files:[preparedExport.file]});document.querySelector('#export-result').innerHTML=`<div class="notice success section"><strong>Review Pack 已準備</strong><p>${esc(preparedExport.file.name)} · ${(bytes.length/1024).toFixed(1)} KB · ${data.attempts.length} 次作答</p><ul class="export-preview">${Object.keys(files).map(f=>`<li>${esc(f)}</li>`).join('')}</ul></div><div class="actions">${supported?button('share-export','分享 ZIP 至 Windows'):''}${button('download-export','下載 ZIP',supported)}${button('download-report','只下載 AI 報告',true)}</div><p class="meta section">交給 AI：「請按 START-HERE.md 開始。」不支援 ZIP 時，可解壓後上傳全部檔案，或用單一 AI 報告。</p>`;return;}
 if(action==='share-export'){if(!preparedExport)throw Error('先準備匯出檔。');await navigator.share({files:[preparedExport.file],title:'FTL Review Pack'});toast('已交給系統分享；請自行確認目的地已收到。');return;}
 if(action==='download-export'){if(!preparedExport)throw Error('先準備匯出檔。');download(preparedExport.file,preparedExport.file.name);return;}
 if(action==='download-report'){if(!preparedExport)throw Error('先準備匯出檔。');download(preparedExport.report,'FTL-AI-Review.md');return;}
 if(action==='storage-status'||action==='persist'){target.disabled=true;const el=document.querySelector('#storage-status');let persistent=await navigator.storage?.persisted?.();if(action==='persist')persistent=await navigator.storage?.persist?.();const est=await navigator.storage?.estimate?.();el.textContent=`持久儲存：${persistent?'已獲允許（仍可由使用者清除）':'未獲允許或不支援；不能保證永久保存'}。${est?.usage?`網站約使用 ${(est.usage/1024/1024).toFixed(2)} MB。`:''}`;return;}
 if(action==='check-update'){target.disabled=true;const el=document.querySelector('#update-result');el.textContent='正在取得版本清單…';try{const m=await fetchManifest();if(compareVersion(m.libraryVersion,baseLibrary.version)<=0){el.textContent='目前已是最新教材。';return;}updateCandidate=m;el.innerHTML=`<div class="notice"><strong>教材 v${esc(m.libraryVersion)}</strong><p>${esc(m.changes||'新版教材')}</p><p>${(m.bytes/1024).toFixed(0)} KB；完整驗證後才啟用。</p></div><div class="actions">${button('install-update','下載及驗證')}</div>`;}catch(err){el.textContent=err.message+' 原教材保持可用。';}return;}
 if(action==='install-update'){if(updating)return;updating=true;target.disabled=true;const el=document.querySelector('#update-result');el.textContent='正在下載及驗證…';try{const l=await verifiedDownload(updateCandidate);const extra=library.scenarios.filter(s=>s.supplementary);validateLibrary({...l,scenarios:[...l.scenarios,...extra]});await store.installLibrary(l);await composeLibrary();el.textContent=`教材 ${l.version} 已啟用。舊作答及草稿保留原版本。`;toast('教材已完整更新');}catch(err){el.textContent=err.message+' 未切換教材。';}finally{updating=false;}return;}
 if(action==='check-app'){target.disabled=true;const el=document.querySelector('#app-update');el.textContent='正在檢查 App…';try{await registration?.update();await new Promise(resolve=>setTimeout(resolve,1500));el.innerHTML=registration?.waiting?button('apply-app','新版本已下載 · 重新開啟'):'目前沒有已準備好的 App 更新。';}catch{el.textContent='未能檢查 App 更新；請確認網絡。';}return;}
 if(action==='apply-app'){await flush();if(registration?.waiting){navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});registration.waiting.postMessage({type:'ACTIVATE'});}return;}
 if(action==='cancel-pack'){packCandidate=null;document.querySelector('#pack-preview').textContent='已取消，沒有修改教材。';document.querySelector('#pack-file').value='';return;}
 if(action==='install-pack'){target.disabled=true;validatePack(packCandidate);await store.put('meta',{id:`pack:${packCandidate.id}`,pack:structuredClone(packCandidate)});packCandidate=null;await composeLibrary();settings();toast('補充題已加入；歷史答案保持不變。');return;}
 }catch(err){if(err.name!=='AbortError')showError(err);}finally{if(target.isConnected)target.disabled=false;}});
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('已交給瀏覽器下載；請確認檔案已保存。');}
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;libraryPage(e.target.value,document.querySelector('#level-filter').value);const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos);}});
document.addEventListener('change',e=>{if(e.target.id==='level-filter')libraryPage(document.querySelector('#search').value,e.target.value);});
window.addEventListener('hashchange',route);window.addEventListener('online',status);window.addEventListener('offline',status);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&currentDraft)queueSave();});
window.addEventListener('pagehide',()=>{if(currentDraft)queueSave();});
async function boot(){try{if(!isSecureContext)throw Error('這個入口不是安全 HTTPS／localhost，無法可靠安裝 PWA');profile=await store.initStore();baseLibrary=await store.activeLibrary();if(!baseLibrary){main.innerHTML=head('首次準備完整教材','下載只需一次。完成後，情境、提示及分析都可以離線使用。');const m=await fetchManifest();await store.installLibrary(await verifiedDownload(m));}if(baseLibrary&&compareVersion(baseLibrary.version,'1.1.0')<0){try{const m=await fetchManifest();await store.installLibrary(await verifiedDownload(m));}catch{toast('仍使用舊教材；連線後到設定更新即可使用新選項。');}}await composeLibrary();await refreshData();await route();status();setupWorker().catch(e=>{swReady=false;status();toast('介面離線準備失敗；請保持連線並重新開啟。');});}catch(e){fatal(e);}}
boot();
